language: node_js
node_js:
- '10.13'
deploy:
  provider: npm
  email: stevepentland@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    repo: stevepentland/swarmer-client-js
